agents_resources: resources/agents
workspace: agent_workspace
max_steps: 100

orchestrator_agent:
  name: ORCHESTRATOR
  model: gpt-4.1-mini
  temperature: 0.2
  base_url: https://api.openai.com/v1
  api_key: OPENAI_API_KEY

agents:
  agent_001:
    name: PROGRAMMER
    model: gpt-4.1-mini
    temperature: 0.2
    base_url: https://api.openai.com/v1
    api_key: OPENAI_API_KEY
